### PR TITLE
Add .github repo

### PR DESCRIPTION
**Pull request by netomi**

### CODE REVIEW

**Review by merks — APPROVED** [review]
Very good!

**Comment by netomi** [comment]
repo created. It might take 1-2 hours till the sync script has setup the required permissions.

**Comment by merks** [comment]
@netomi @jonahgraham 

So later today, when we want to add a new "simrel" repository, or whatever we decide to name it, we can add it ourselves like this,right?

**Comment by netomi** [comment]
Sure, you can request everything yourself. If you need any help, let me know.

**Pull request merged**
