### PR TITLE
Provide better descriptions for the  repositories

### PR DESCRIPTION
**Pull request by merks**

### CODE REVIEW

**Comment by netomi** [comment]
change applied.

**Comment by merks** [comment]
I really feel way more empowered with this new approach!

**Comment by netomi** [comment]
We are happy that project members are starting to use and like the approach. It certainly feels natural for somebody writing code to also request configuration changes that way.

There are a couple of things that we would like to add: https://gitlab.eclipse.org/eclipsefdn/security/otterdog
You can also suggest features or changes yourself.

Currently, we also work on providing a more details documentation of the tool and the way to configure stuff, the latest version can be accessed at https://otterdog.readthedocs.io/en/latest/

**Comment by merks** [comment]
It's great.   Of course better documentation will be a good thing, i.e., all the properties one can use to configure things...

**Comment by netomi** [comment]
All supported settings should be listed here: https://gitlab.eclipse.org/eclipsefdn/security/otterdog#supported-settings
To know what value is defined for each setting in the default config, you can take a look here: https://github.com/EclipseFdn/otterdog-defaults/blob/main/otterdog-defaults.libsonnet

Its not very user friendly, we are on it to improve the documentation at http://otterdog.readthedocs.io

**Comment by merks** [comment]
Silly/stupid me!  I am on my small laptop monitor and I did not scroll far enough to notice the extensive README.md.  😜

**Comment by merks** [comment]
BTW, I was reviewing the settings and then when I look at Oomph's configuration, I'm not sure why this repo has discussions:

https://github.com/eclipse-oomph/oomph

but this one does not:

https://github.com/eclipse-oomph/oomph.incubator

yet the settings look the same:
```
    orgs.newRepo('oomph') {
      allow_update_branch: false,
      default_branch: "master",
      web_commit_signoff_required: false,
    },
    orgs.newRepo('oomph.incubator') {
      allow_update_branch: false,
      default_branch: "master",
      web_commit_signoff_required: false,
    },
```
Maybe a missing or undocumented configuration property?

**Comment by netomi** [comment]
The reason for that is that that the oomph repository is being set up as the repo to host organization discussions for eclipse-oomph:

image

Something the tool does not yet take into account but should be part of the configuration.

**Pull request merged**
